agenda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('clientes.urls', namespace='clientes')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/urls.py
from django.conf.urls import url	
from . import views
from .views import ListaCliente,DetalleCliente,agregar_cliente,borrar_cliente

urlpatterns=[
	url(r'^$', views.ListaCliente.as_view(), name='clientes'),
	url(r'^cliente/(?P<pk>[0-9]+)/$', views.DetalleCliente.as_view(), name="detalle"),
	url(r'^cliente/agregar', views.agregar_cliente, name="agregar"),
	url(r'^cliente/(?P<id>\d+)$', views.borrar_cliente, name="borrar"),
	url(r'^cliente/(?P<pk>\d+)/update/$', views.ClienteUpdate.as_view(), name='update'),

]

clientes/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models


class Cliente(models.Model):

	nombre = models.CharField(max_length=255)
	telefono= models.IntegerField(unique=True)
	direccion= models.TextField(max_length=255)
	foto= models.ImageField(blank=True)

	def __str__(self):
		return self.nombre
	class Meta:
		ordering = ('id' , )

	# def get_absolute_url(self):
	# 	return reverse('')

clientes/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
	class Meta:
		model = Cliente
		fields = '__all__'

clientes/views.py
from django.shortcuts import render, redirect
from .models import Cliente
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Cliente
from .forms import ClienteForm
from django.core.urlresolvers import reverse_lazy

from django.views.generic.edit import UpdateView

class ClienteUpdate(UpdateView):
    model = Cliente
    fields=('nombre', 'telefono', 'direccion','foto')
    success_url = reverse_lazy('clientes:clientes')
    	

class ListaCliente(ListView):
	model= Cliente


class DetalleCliente(DetailView):
	model = Cliente

def agregar_cliente(request):

	if request.method=='POST':
		form=ClienteForm(request.POST, request.FILES)
		if form.is_valid():
			cliente = form.save()
			cliente.save()
			return HttpResponseRedirect('/')
	else:
		form = ClienteForm()		
		

	template=loader.get_template('agregar.html')
	context={
		'form': form
	}
	return HttpResponse(template.render(context,request))	

def borrar_cliente(request, id):
	cliente = Cliente.objects.get(id=id)
	cliente.delete()
		
	return HttpResponseRedirect('/')		

templates/agregar.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Cliente nuevo</title>
</head>
<body>
	<h1>Agregar</h1>
	<form method="POST" enctype="multipart/form-data">
		{%csrf_token%} <!-- seguridad en formularios de django, ponerlos siempre que tengamos un post -->
		{{form.as_p}} <!-- pone en lista -->
			
			<button type='submit'>Guardar</button>
		
	</form>
</body>
</html>

templates/clientes/cliente_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title> {{ cliente.nombre }}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
	<img src="{{ cliente.foto.url }}" alt="">
    <h1>{{ cliente.nombre }}</h1>
    <h2>Telefono: {{ cliente.telefono }}</h2>
	<h3>Direccion: {{cliente.direccion}}</h3>

	<a href="{% url 'clientes:update' object.id %}">Editar</a>  |  
	<a href="{%url 'clientes:borrar' object.id%}">Eliminar</a>
    

    
</body>
</html>

templates/clientes/cliente_form.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Cliente nuevo</title>
</head>
<body>
	<h1>Actualizar</h1>
	<form  method="POST" enctype="multipart/form-data">
		{%csrf_token%} <!-- seguridad en formularios de django, ponerlos siempre que tengamos un post -->
		{{form.as_p}} <!-- pone en lista -->
			
			<button type='submit'>Guardar</button>
			 
	</form>
</body>
</html>

templates/clientes/cliente_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>Clientes</title>
	<link rel="stylesheet" href="{%static 'css/estilo.css'%}">
</head>
<body>
	<h1>Clientes</h1>
	<a href="{%url 'clientes:agregar'%}">Agregar clientes</a>
	<ul>
		{% for cl in object_list %}
		<div id= "objeto">
		<li>
			<img class="elementos" src="{{cl.foto.url}}" alt="">
			<a class="" ="elementos" href="{%url 'clientes:detalle' cl.id%}">{{ cl.nombre}}</a>
			
			{# <a href="{%url 'clientes:borrar' cl.id%}">Borrar cliente</a> #}
			

		</li>
		</div>
		{%endfor%}
	</ul>
	
</body>
</html>

templates/editar.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Cliente nuevo</title>
</head>
<body>
	<h1>Actualizar</h1>
	<form method="POST" enctype="multipart/form-data">
		{%csrf_token%} <!-- seguridad en formularios de django, ponerlos siempre que tengamos un post -->
		{{form.as_p}} <!-- pone en lista -->
		
			<button type='submit'>Guardar</button>
		
	</form>
</body>
</html>